# Generated by Django 5.1.2 on 2026-05-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_id_alter_savedvideo_id_alter_video_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedvideo',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
